chipset = "sm8450"

[bootimg]
version = 4
kernel_source = "uniloader"
base = 0x0
kernel = 0x8000
ramdisk = 0x02000000
dtb = 0x01f00000
second = 0
tags = 0x01e00000
pagesize = 4096

[[device]]
vendor = "samsung"
model = "gts8wifi"
dtb_vendor = "galaxy"
dtb_model = "tab-s8-5g"
append = "clk_ignore_unused pd_ignore_unused"
